### ISSUE TITLE
Comments are broken

### ISSUE THREAD

**Issue by Osiris-Team** [Carleslc/Simple-YAML#44]
```txt
Error Message: while scanning a simple key
 in 'string', line 15, column 1:
    ys to 0 if you want to keep your ... 
    ^
could not find expected ':'
 in 'string', line 16, column 13:
        max-days: 7
                ^
```
Yaml file: (max-days duplicated itself and the #  and half of the comment disappeared)
```yaml
  plugins-backup:
    # Backups your plugins folder before startup to /autoplug-backups/plugins/...zip
    enable: true
    max-days: 7
ys to 0 if you want to keep your backups forever.
    max-days: 7
```
