### ISSUE TITLE
Can't properly set comments on nested options

### ISSUE THREAD

**Issue by re-ovo** [Carleslc/Simple-YAML#56]
I am using this code to set comments:
```kotlin
this.path(it).comment(comment, YamlCommentFormat.BLANK_LINE)
```

But the first line comment is not placed correctly: (`sync.sync-config`)
```yaml
# This is a configuration file synchronization feature, you can configure RikkaAC on one server, and
# then use "/rikka sync" to synchronize to all RikkaAC connected to the same database, this is very
# convenient for some large networks
sync:
# Whether the sync feature should sync config.yml
  # (!) Note that this will override the storage setting
  # (!) Better to not change storage setting if you want to sync
  sync-config: true
```
